<?php

namespace app\models;

class SystemReports extends \koolreport\KoolReport
{
    protected function settings()
    {
        return parent::settings(); // TODO: Change the autogenerated stub
    }
    protected function setup()
    {
        parent::setup(); // TODO: Change the autogenerated stub
    }

}